FROM rustlang/rust:nightly AS builder
WORKDIR /app

# Copy all source files
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim AS runtime
# Install ca-certificates for HTTPS requests
RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
# Copy the binary from builder stage
COPY --from=builder /app/target/release/the-beaconator /app/the-beaconator
# Copy the abis directory
COPY --from=builder /app/abis /app/abis

# Accept build arguments for environment variables
ARG RPC_URL
ARG PRIVATE_KEY
ARG SENTRY_DSN
ARG ENV
ARG BEACONATOR_ACCESS_TOKEN
ARG BEACON_FACTORY_ADDRESS
ARG PERPCITY_REGISTRY_ADDRESS
ARG PERP_MANAGER_ADDRESS
ARG USDC_ADDRESS
ARG FEES_MODULE_ADDRESS
ARG MARGIN_RATIOS_MODULE_ADDRESS
ARG LOCKUP_PERIOD_MODULE_ADDRESS
ARG SQRT_PRICE_IMPACT_LIMIT_MODULE_ADDRESS

# Set environment variables for Rocket and application
ENV ROCKET_ADDRESS=::
ENV ROCKET_PORT=${PORT:-8000}
ENV RPC_URL=${RPC_URL}
ENV PRIVATE_KEY=${PRIVATE_KEY}
ENV SENTRY_DSN=${SENTRY_DSN}
ENV ENV=${ENV}
ENV BEACONATOR_ACCESS_TOKEN=${BEACONATOR_ACCESS_TOKEN}
ENV BEACON_FACTORY_ADDRESS=${BEACON_FACTORY_ADDRESS}
ENV PERPCITY_REGISTRY_ADDRESS=${PERPCITY_REGISTRY_ADDRESS}
ENV PERP_MANAGER_ADDRESS=${PERP_MANAGER_ADDRESS}
ENV USDC_ADDRESS=${USDC_ADDRESS}
ENV FEES_MODULE_ADDRESS=${FEES_MODULE_ADDRESS}
ENV MARGIN_RATIOS_MODULE_ADDRESS=${MARGIN_RATIOS_MODULE_ADDRESS}
ENV LOCKUP_PERIOD_MODULE_ADDRESS=${LOCKUP_PERIOD_MODULE_ADDRESS}
ENV SQRT_PRICE_IMPACT_LIMIT_MODULE_ADDRESS=${SQRT_PRICE_IMPACT_LIMIT_MODULE_ADDRESS}

# Expose the port (Railway will use the PORT environment variable)
EXPOSE ${PORT:-8000}
# Run the binary
CMD ["./the-beaconator"]