FROM rustlang/rust:nightly

ARG PORT
ARG RPC_URL
ARG PRIVATE_KEY
ARG SENTRY_DSN
ARG ENV

ENV ROCKET_ADDRESS=0.0.0.0
ENV ENV=$ENV
ENV RPC_URL=$RPC_URL
ENV PRIVATE_KEY=$PRIVATE_KEY
ENV SENTRY_DSN=$SENTRY_DSN

WORKDIR /app
COPY . .

RUN cargo build --release

CMD ROCKET_PORT=$PORT ./target/release/rocket