/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Returns API summary and available endpoints.
         *
         *     Provides an overview of The Beaconator API including total endpoints, working endpoints, and not yet implemented endpoints. This endpoint does not require authentication.
         */
        get: operations["routes_info_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/all_beacons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lists all registered beacons.
         *
         *     This endpoint is not yet implemented and returns a placeholder response. Requires Bearer token authentication.
         */
        get: operations["routes_info_all_beacons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates a new beacon via the beacon factory.
         *
         *     Creates a beacon using the beacon factory contract for the authenticated wallet address.
         */
        post: operations["routes_beacon_create_beacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register_beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Registers an existing beacon with the registry.
         *
         *     Registers a previously created beacon with the PerpCity registry contract.
         */
        post: operations["routes_beacon_register_beacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_perpcity_beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates a single PerpCity beacon.
         *
         *     Creates a new beacon via the beacon factory and registers it with the PerpCity registry. Returns the address of the created beacon on success.
         */
        post: operations["routes_beacon_create_perpcity_beacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batch_create_perpcity_beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates multiple PerpCity beacons in a batch operation.
         *
         *     Creates the specified number of beacons (1-100) via the beacon factory and registers them with the PerpCity registry. Returns details about successful and failed creations.
         */
        post: operations["routes_beacon_batch_create_perpcity_beacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deploy_perp_for_beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Deploys a perpetual contract for a specific beacon.
         *
         *     Creates a new perpetual pool using the PerpManager contract for the specified beacon address. Returns the perp ID, PerpManager address, and transaction hash on success.
         */
        post: operations["routes_perp_deploy_perp_for_beacon_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batch_deploy_perps_for_beacons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Deploys perpetual contracts for multiple beacons in a batch operation.
         *
         *     Creates perpetual pools for each specified beacon address using the PerpManager contract. Returns detailed results including perp IDs for successful deployments.
         */
        post: operations["routes_perp_batch_deploy_perps_for_beacons"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deposit_liquidity_for_perp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Deposits liquidity for a specific perpetual contract.
         *
         *     Approves USDC spending and deposits the specified margin amount as liquidity for the given perp ID. Returns the maker position ID and transaction hashes.
         */
        post: operations["routes_perp_deposit_liquidity_for_perp_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batch_deposit_liquidity_for_perps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Deposits liquidity for multiple perpetual contracts in a batch operation.
         *
         *     Processes multiple liquidity deposits, each with their own perp ID and margin amount. Returns detailed results for each deposit attempt.
         */
        post: operations["routes_perp_batch_deposit_liquidity_for_perps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update_beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Updates a beacon with new data using a zero-knowledge proof.
         *
         *     Validates the provided proof and public signals, then updates the beacon's data. Returns the transaction hash on success.
         */
        post: operations["routes_beacon_update_beacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batch_update_beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Updates multiple beacons with new data using zero-knowledge proofs.
         *
         *     Processes a batch of beacon updates, each with their own proof and public signals. Returns detailed results for each update attempt.
         */
        post: operations["routes_beacon_batch_update_beacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fund_guest_wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Funds a guest wallet with USDC and ETH.
         *
         *     Transfers the specified amounts of USDC and ETH from the beaconator wallet to the guest wallet address. Validates transfer limits and available balances.
         */
        post: operations["routes_wallet_fund_guest_wallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_verifiable_beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates a verifiable beacon with Halo2 proof verification.
         *
         *     Creates a new verifiable beacon using the DichotomousBeaconFactory with the specified verifier contract address, initial data value, and TWAP cardinality.
         */
        post: operations["routes_beacon_create_verifiable_beacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard API response wrapper */
        ApiResponse_for_ApiSummary: {
            /** @description Whether the request succeeded */
            success: boolean;
            /** @description Response data (null if request failed) */
            data?: components["schemas"]["ApiSummary"] | null;
            /** @description Human-readable message about the result */
            message: string;
        };
        ApiSummary: {
            /** Format: uint */
            total_endpoints: number;
            /** Format: uint */
            working_endpoints: number;
            /** Format: uint */
            not_implemented: number;
            /** Format: uint */
            deprecated: number;
            endpoints: components["schemas"]["EndpointInfo"][];
        };
        /** @description API endpoint information for documentation */
        EndpointInfo: {
            method: string;
            path: string;
            description: string;
            requires_auth: boolean;
            status: components["schemas"]["EndpointStatus"];
        };
        /** @enum {string} */
        EndpointStatus: "Working" | "NotImplemented" | "Deprecated";
        /** @description Standard API response wrapper */
        ApiResponse_for_Array_of_String: {
            /** @description Whether the request succeeded */
            success: boolean;
            /** @description Response data (null if request failed) */
            data?: string[] | null;
            /** @description Human-readable message about the result */
            message: string;
        };
        /** @description Standard API response wrapper */
        ApiResponse_for_String: {
            /** @description Whether the request succeeded */
            success: boolean;
            /** @description Response data (null if request failed) */
            data?: string | null;
            /** @description Human-readable message about the result */
            message: string;
        };
        /** @description Create a new beacon (not yet implemented) */
        CreateBeaconRequest: {
            /** @description Placeholder field until implementation is complete */
            placeholder: string;
        };
        /** @description Register an existing beacon with the registry */
        RegisterBeaconRequest: {
            /** @description Ethereum address of the beacon contract */
            beacon_address: string;
            /** @description Ethereum address of the beacon registry contract */
            registry_address: string;
        };
        /** @description Standard API response wrapper */
        ApiResponse_for_BatchCreatePerpcityBeaconResponse: {
            /** @description Whether the request succeeded */
            success: boolean;
            /** @description Response data (null if request failed) */
            data?: components["schemas"]["BatchCreatePerpcityBeaconResponse"] | null;
            /** @description Human-readable message about the result */
            message: string;
        };
        /** @description Response from batch Perpcity beacon creation */
        BatchCreatePerpcityBeaconResponse: {
            /**
             * Format: uint32
             * @description Number of successfully created beacons
             */
            created_count: number;
            /** @description List of beacon addresses (hex strings with 0x prefix) */
            beacon_addresses: string[];
            /**
             * Format: uint32
             * @description Number of failed creations
             */
            failed_count: number;
            /** @description Error messages for failed creations */
            errors: string[];
        };
        /** @description Batch create multiple Perpcity beacons */
        BatchCreatePerpcityBeaconRequest: {
            /**
             * Format: uint32
             * @description Number of beacons to create (1-100)
             */
            count: number;
        };
        /** @description Standard API response wrapper */
        ApiResponse_for_DeployPerpForBeaconResponse: {
            /** @description Whether the request succeeded */
            success: boolean;
            /** @description Response data (null if request failed) */
            data?: components["schemas"]["DeployPerpForBeaconResponse"] | null;
            /** @description Human-readable message about the result */
            message: string;
        };
        /** @description Response from deploying a perpetual contract */
        DeployPerpForBeaconResponse: {
            /** @description 32-byte perpetual pool identifier (hex string with 0x prefix) */
            perp_id: string;
            /** @description Address of the PerpManager contract */
            perp_manager_address: string;
            /** @description Transaction hash */
            transaction_hash: string;
        };
        /** @description Deploy a perpetual contract for a specific beacon */
        DeployPerpForBeaconRequest: {
            /** @description Ethereum address of the beacon contract */
            beacon_address: string;
            /** @description Address of the fees configuration module */
            fees_module: string;
            /** @description Address of the margin ratios configuration module */
            margin_ratios_module: string;
            /** @description Address of the lockup period configuration module */
            lockup_period_module: string;
            /** @description Address of the sqrt price impact limit configuration module */
            sqrt_price_impact_limit_module: string;
            /** @description Starting sqrt price in Q96 format as string */
            starting_sqrt_price_x96: string;
        };
        /** @description Standard API response wrapper */
        ApiResponse_for_BatchDeployPerpsForBeaconsResponse: {
            /** @description Whether the request succeeded */
            success: boolean;
            /** @description Response data (null if request failed) */
            data?: components["schemas"]["BatchDeployPerpsForBeaconsResponse"] | null;
            /** @description Human-readable message about the result */
            message: string;
        };
        /** @description Response from batch perpetual deployment */
        BatchDeployPerpsForBeaconsResponse: {
            /**
             * Format: uint32
             * @description Number of successfully deployed perpetuals
             */
            deployed_count: number;
            /** @description List of perpetual pool IDs (hex strings with 0x prefix) */
            perp_ids: string[];
            /**
             * Format: uint32
             * @description Number of failed deployments
             */
            failed_count: number;
            /** @description Error messages for failed deployments */
            errors: string[];
        };
        /** @description Batch deploy perpetual contracts for multiple beacons */
        BatchDeployPerpsForBeaconsRequest: {
            /** @description List of beacon addresses to deploy perps for */
            beacon_addresses: string[];
            /** @description Address of the fees configuration module */
            fees_module: string;
            /** @description Address of the margin ratios configuration module */
            margin_ratios_module: string;
            /** @description Address of the lockup period configuration module */
            lockup_period_module: string;
            /** @description Address of the sqrt price impact limit configuration module */
            sqrt_price_impact_limit_module: string;
            /** @description Starting sqrt price in Q96 format as string */
            starting_sqrt_price_x96: string;
        };
        /** @description Standard API response wrapper */
        ApiResponse_for_DepositLiquidityForPerpResponse: {
            /** @description Whether the request succeeded */
            success: boolean;
            /** @description Response data (null if request failed) */
            data?: components["schemas"]["DepositLiquidityForPerpResponse"] | null;
            /** @description Human-readable message about the result */
            message: string;
        };
        /** @description Response from depositing liquidity to a perpetual */
        DepositLiquidityForPerpResponse: {
            /** @description Maker position ID from MakerPositionOpened event */
            maker_position_id: string;
            /** @description USDC approval transaction hash */
            approval_transaction_hash: string;
            /** @description Liquidity deposit transaction hash */
            deposit_transaction_hash: string;
        };
        /** @description Deposit liquidity for a perpetual contract */
        DepositLiquidityForPerpRequest: {
            /** @description Perpetual pool ID as hex string (with or without 0x prefix) */
            perp_id: string;
            /**
             * @description USDC margin amount in 6 decimals (e.g., "50000000" for 50 USDC)
             *
             *     Margin constraints are enforced by on-chain modules. The margin ratios module defines minimum and maximum allowed margins based on market configuration.
             *
             *     Current liquidity scaling: margin × 500,000 = final liquidity amount
             */
            margin_amount_usdc: string;
            /** @description Optional holder address (defaults to wallet address if not provided) */
            holder?: string | null;
            /** @description Maximum amount of token0 to deposit (slippage protection), optional */
            max_amt0_in?: string | null;
            /** @description Maximum amount of token1 to deposit (slippage protection), optional */
            max_amt1_in?: string | null;
            /**
             * Format: int32
             * @description Tick spacing for the liquidity position (defaults to 30)
             */
            tick_spacing?: number | null;
            /**
             * Format: int32
             * @description Lower tick bound for the liquidity position (defaults to 24390)
             */
            tick_lower?: number | null;
            /**
             * Format: int32
             * @description Upper tick bound for the liquidity position (defaults to 53850)
             */
            tick_upper?: number | null;
        };
        /** @description Standard API response wrapper */
        ApiResponse_for_BatchDepositLiquidityForPerpsResponse: {
            /** @description Whether the request succeeded */
            success: boolean;
            /** @description Response data (null if request failed) */
            data?: components["schemas"]["BatchDepositLiquidityForPerpsResponse"] | null;
            /** @description Human-readable message about the result */
            message: string;
        };
        /** @description Response from batch liquidity deposit operation */
        BatchDepositLiquidityForPerpsResponse: {
            /**
             * Format: uint32
             * @description Number of successful deposits
             */
            deposited_count: number;
            /** @description List of maker position IDs */
            maker_position_ids: string[];
            /**
             * Format: uint32
             * @description Number of failed deposits
             */
            failed_count: number;
            /** @description Error messages for failed deposits */
            errors: string[];
        };
        /** @description Batch deposit liquidity for multiple perpetual contracts */
        BatchDepositLiquidityForPerpsRequest: {
            /** @description List of liquidity deposits to process */
            liquidity_deposits: components["schemas"]["DepositLiquidityForPerpRequest"][];
        };
        /** @description Update an existing beacon with new data using a zero-knowledge proof */
        UpdateBeaconRequest: {
            /** @description Ethereum address of the beacon contract (with or without 0x prefix) */
            beacon_address: string;
            /** @description Zero-knowledge proof data as hex string (with 0x prefix) */
            proof: string;
            /** @description Public signals from the proof as hex string (with 0x prefix), contains the new data value */
            public_signals: string;
        };
        /** @description Standard API response wrapper */
        ApiResponse_for_BatchUpdateBeaconResponse: {
            /** @description Whether the request succeeded */
            success: boolean;
            /** @description Response data (null if request failed) */
            data?: components["schemas"]["BatchUpdateBeaconResponse"] | null;
            /** @description Human-readable message about the result */
            message: string;
        };
        /** @description Response from batch beacon update operation */
        BatchUpdateBeaconResponse: {
            /** @description Individual results for each beacon */
            results: components["schemas"]["BeaconUpdateResult"][];
            /**
             * Format: uint
             * @description Total number of updates requested
             */
            total_requested: number;
            /**
             * Format: uint
             * @description Number of successful updates
             */
            successful_updates: number;
            /**
             * Format: uint
             * @description Number of failed updates
             */
            failed_updates: number;
        };
        /** @description Result of updating a single beacon */
        BeaconUpdateResult: {
            /** @description Address of the beacon that was updated */
            beacon_address: string;
            /** @description Whether the update succeeded */
            success: boolean;
            /** @description Transaction hash (if successful) */
            transaction_hash?: string | null;
            /** @description Error message (if failed) */
            error?: string | null;
        };
        /** @description Batch update multiple beacons with zero-knowledge proofs */
        BatchUpdateBeaconRequest: {
            /** @description List of beacon updates to process */
            updates: components["schemas"]["BeaconUpdateData"][];
        };
        /** @description Beacon update data for batch operations */
        BeaconUpdateData: {
            /** @description Ethereum address of the beacon contract (with or without 0x prefix) */
            beacon_address: string;
            /** @description Zero-knowledge proof data as hex string (with 0x prefix) */
            proof: string;
            /** @description Public signals from the proof as hex string (with 0x prefix) */
            public_signals: string;
        };
        /** @description Fund a guest wallet with USDC and ETH */
        FundGuestWalletRequest: {
            /** @description Ethereum address of the wallet to fund */
            wallet_address: string;
            /** @description USDC amount in 6 decimals (e.g., "100000000" for 100 USDC) */
            usdc_amount: string;
            /** @description ETH amount in wei (e.g., "1000000000000000" for 0.001 ETH) */
            eth_amount: string;
        };
        /** @description Create a verifiable beacon with zero-knowledge proof support and TWAP */
        CreateVerifiableBeaconRequest: {
            /** @description Halo2 verifier contract address */
            verifier_address: string;
            /** @description Initial data value (MUST be pre-scaled by 2^96 if representing a decimal) */
            initial_data: string;
            /**
             * Format: uint32
             * @description Initial TWAP observation slots (typically 100-1000)
             */
            initial_cardinality: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    routes_info_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_ApiSummary"];
                };
            };
        };
    };
    routes_info_all_beacons: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_Array_of_String"];
                };
            };
        };
    };
    routes_beacon_create_beacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBeaconRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_String"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_beacon_register_beacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterBeaconRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_String"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_beacon_create_perpcity_beacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_String"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_beacon_batch_create_perpcity_beacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreatePerpcityBeaconRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_BatchCreatePerpcityBeaconResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_perp_deploy_perp_for_beacon_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployPerpForBeaconRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_DeployPerpForBeaconResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_perp_batch_deploy_perps_for_beacons: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeployPerpsForBeaconsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_BatchDeployPerpsForBeaconsResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_perp_deposit_liquidity_for_perp_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepositLiquidityForPerpRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_DepositLiquidityForPerpResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_perp_batch_deposit_liquidity_for_perps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDepositLiquidityForPerpsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_BatchDepositLiquidityForPerpsResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_beacon_update_beacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBeaconRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_String"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_beacon_batch_update_beacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchUpdateBeaconRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_BatchUpdateBeaconResponse"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_wallet_fund_guest_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundGuestWalletRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_String"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_String"];
                };
            };
        };
    };
    routes_beacon_create_verifiable_beacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVerifiableBeaconRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_for_String"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
